# Generated by Django 2.0 on 2018-02-03 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=0, editable=False, verbose_name='Ilość')),
                ('ilosc_min', models.IntegerField(default=0, verbose_name='Minimalna ilość')),
                ('ilosc_max', models.IntegerField(default=0, verbose_name='Maksymalna ilość')),
                ('wolny', models.IntegerField(default=0, editable=False)),
                ('zamowiony', models.IntegerField(default=0, editable=False)),
                ('sprzedany', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='MagazynPrzyjecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=0, verbose_name='Ilość')),
                ('kiedy', models.DateTimeField(auto_now_add=True)),
                ('kto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('magazyn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produkt.Magazyn')),
            ],
        ),
        migrations.CreateModel(
            name='MagazynWydanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=0, editable=False, verbose_name='Ilość')),
                ('kiedy', models.DateTimeField(auto_now_add=True)),
                ('kto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('magazyn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produkt.Magazyn')),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=300)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('opis', models.TextField(blank=True)),
                ('marka', models.CharField(max_length=300)),
                ('obraz', models.ImageField(blank=True, null=True, upload_to='obrazy/')),
            ],
            options={
                'ordering': ['nazwa', 'marka'],
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zamowienia', models.CharField(max_length=50, verbose_name='numer zamówienia')),
                ('klient', models.CharField(max_length=300)),
                ('adres', models.CharField(max_length=500)),
                ('wysylka_typ', models.IntegerField(choices=[(1, 'kurier'), (2, 'list ekonomiczny'), (3, 'list priorytetowy'), (5, 'odbiór osobisty'), (5, 'paczkomat')], default=2, verbose_name='typ wysyłki')),
                ('wysylka_adres', models.CharField(blank=True, help_text='wypełnij jeśli adres wysyłki jest inny niż adres klienta', max_length=500, verbose_name='adres wysyłki')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.PositiveIntegerField(blank=True, null=True, verbose_name='numer telefonu')),
                ('zrealizowane', models.BooleanField(default=False, verbose_name='czy zrealizowane')),
                ('opis', models.TextField(blank=True, verbose_name='Dodatkowe informacje')),
                ('komentarz', models.TextField(blank=True, help_text='nie widzialny dla klienta', verbose_name='Komentarz pracownika')),
                ('komentarz_klient', models.TextField(blank=True, verbose_name='Dodatkowe infomacje klienta')),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('data_realizacji', models.DateTimeField(editable=False, null=True)),
                ('realizacja_kto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zamowienie_realizacja_kto_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_zamowienia'],
            },
        ),
        migrations.CreateModel(
            name='ZamowienieProdukt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('ilosc', models.PositiveIntegerField(default=0, verbose_name='ilość')),
                ('komentarz', models.TextField(blank=True)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produkt.Produkt')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produkt.Zamowienie')),
            ],
            options={
                'ordering': ['produkt__nazwa', 'produkt__marka'],
            },
        ),
        migrations.CreateModel(
            name='ZamowienieStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'oczekuje'), (2, 'w realizacji'), (3, 'wysłano'), (4, 'anulowane')])),
                ('komentarz', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now=True)),
                ('kto', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zamowienie_status_kto_set', to=settings.AUTH_USER_MODEL)),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produkt.Zamowienie')),
            ],
            options={
                'ordering': ['zamowienie', '-data'],
            },
        ),
        migrations.AddField(
            model_name='magazyn',
            name='produkt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='produkt.Produkt'),
        ),
    ]
