# Generated by Django 2.0 on 2018-02-03 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temat', models.CharField(blank=True, max_length=300)),
                ('tresc', models.TextField(blank=True)),
                ('odczytana', models.BooleanField(default=False)),
                ('data_nadania', models.DateTimeField(auto_now_add=True)),
                ('zalacznik', models.FileField(blank=True, null=True, upload_to='pliki/')),
                ('nadawca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nadawcawiadomosc_set', to=settings.AUTH_USER_MODEL)),
                ('odbiorca_list', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['odczytana', '-data_nadania'],
            },
        ),
    ]
